package identity

import (
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"errors"
	"fmt"
	"strconv"
	"strings"
)

// The key-material model. A presented API key is a token with the grammar
//
//	gw_<key-id>_<secret>
//
// where <key-id> is the key's RFC 4122 UUID and <secret> is the base64url
// (unpadded) rendering of 32 uniformly random bytes — 256 bits of entropy,
// generated by crypto/rand at mint time. SHA-256 of the raw secret bytes is
// the digest a credential record stores; equality of two fixed-width
// digests is decided by subtle.ConstantTimeCompare, never by ==.
//
// Why SHA-256 and not a password hash: the secret is uniformly random at
// 256 bits, so there is no dictionary to slow down and no benefit from a
// memory-hard function's cost on the runtime hot path. A preimage-resistant
// digest of a high-entropy secret is the standard machinery, and ADR 0006 §9
// already pins exactly this shape for the management-plane service
// credentials. Why the digest lives outside this database: ADR 0006 §8 — the
// Control Plane keeps the ownership record; the Data Plane's credential
// record keeps the digest, unreachable from here.

const (
	// TokenBrand is the fixed first segment of every token this gateway
	// mints. It makes a stray value recognisable as an attempt at a gateway
	// key rather than some other bearer credential.
	TokenBrand = "gw"

	// SecretEntropyBytes is the secret's size in raw bytes. 32 bytes of
	// crypto/rand output is 256 bits — beyond brute force for any
	// foreseeable adversary, and exactly one base64url block short of
	// nothing: it encodes to 43 characters, unpadded.
	SecretEntropyBytes = 32

	// secretEncodedLen is base64.RawURLEncoding.EncodedLen(SecretEntropyBytes).
	// ParseToken checks it so a truncated or padded secret fails closed.
	secretEncodedLen = 43
)

// errSecretLength is a construction-time guard local to this file's grammar
// checks; the caller-facing sentinels live in errors.go and this one is
// always wrapped inside them.
var errSecretLength = errors.New("identity: secret must decode to 32 bytes")

// Secret is one minted key secret. The bytes are never exported: nothing
// outside this package can print, marshal or compare them except through
// the accessors below, every one of which is deliberate. String and GoString
// redact so a log line, an error wrap or a %v of a struct holding a Secret
// shows "redacted" instead of credential material; MarshalText refuses so an
// accidental JSON round-trip cannot smuggle the bytes into a snapshot.
type Secret struct {
	bytes []byte
}

// GenerateSecret draws a fresh secret from crypto/rand. Failure is
// effectively impossible on a healthy kernel but is reported, never
// swallowed — minting must not proceed with a weaker secret and must not
// pretend one was made.
func GenerateSecret() (Secret, error) {
	b := make([]byte, SecretEntropyBytes)
	if _, err := rand.Read(b); err != nil {
		return Secret{}, fmt.Errorf("identity: generate secret: %w", err)
	}
	return Secret{bytes: b}, nil
}

// NewSecretFromTokenBytes rebuilds a Secret from the raw bytes decoded out
// of a presented token. It is the only way a Secret enters the system
// besides GenerateSecret, and it enforces the same size bar so a
// wrong-length presentation is malformed, not merely unmatched.
func NewSecretFromTokenBytes(raw []byte) (Secret, error) {
	if len(raw) != SecretEntropyBytes {
		return Secret{}, fmt.Errorf("identity: %w: got %d", errSecretLength, len(raw))
	}
	return Secret{bytes: raw}, nil
}

// Digest returns the SHA-256 of the secret's raw bytes. This is the value a
// credential record stores — never the secret itself.
func (s Secret) Digest() Digest {
	sum := sha256.Sum256(s.bytes)
	return Digest(sum)
}

// String implements fmt.Stringer with a redaction, so every accidental
// printing path — %v, %s, error wrapping, struct dumps — shows a marker
// instead of credential material.
func (s Secret) String() string { return "secret(redacted)" }

// GoString covers the %#v debugging verb with the same redaction.
func (s Secret) GoString() string { return "identity.Secret{redacted}" }

// MarshalText refuses: any encoder that reaches for textual form (JSON,
// maps, structured logs) gets an error rather than credential bytes.
func (s Secret) MarshalText() ([]byte, error) {
	return nil, errors.New("identity: secret must never be serialised")
}

// Digest is a SHA-256 output: fixed-width, byte-comparable, and not itself
// secret material — knowing it does not let anyone present the key, which is
// exactly why it may be stored in a credential record while the secret may
// not. Hex is provided for the places a digest must be rendered (the future
// credential projection delivers it in this form).
type Digest [sha256.Size]byte

// Hex renders the digest lowercase-hex, the canonical text form for storage
// and transport. Harmless to log; not credential material.
func (d Digest) Hex() string {
	const hexDigits = "0123456789abcdef"
	out := make([]byte, 0, 2*sha256.Size)
	for _, b := range d {
		out = append(out, hexDigits[b>>4], hexDigits[b&0x0f])
	}
	return string(out)
}

// EqualDigests compares two digests in constant time. The widths are fixed
// by the type — [32]byte, not slices — so the comparison cannot leak through
// an early exit on length, and the branch on its result happens only after
// the full comparison has run.
func EqualDigests(a, b Digest) bool {
	return subtle.ConstantTimeCompare(a[:], b[:]) == 1
}

// CompareAgainstDummyDigest runs a full constant-time comparison of the
// presented secret's digest against the zero digest, and returns a value
// callers must ignore. A verifier that skips the comparison when a key id
// has no record runs measurably faster on the miss path, which turns timing
// into a key-id existence oracle; calling this on that path keeps the two
// paths' work identical. See VerifyCredential for the policy that pairs it
// with ErrUnknownCredential.
func CompareAgainstDummyDigest(s Secret) bool {
	return EqualDigests(s.Digest(), Digest{})
}

// TokenPrefix renders the public token prefix for a key id: brand and id,
// no secret. It is what consoles show and what the ownership record stores.
func TokenPrefix(id APIKeyID) string {
	return TokenBrand + "_" + string(id) + "_"
}

// FormatToken assembles a full token from its parts at mint time. It is the
// only producer of complete tokens; nothing ever re-formats one later, and
// the returned string is handed to the operator exactly once. Its errors are
// plain programming-error wraps — the arguments come from mint itself, not
// from an untrusted presentation, so the presentation sentinels do not
// apply.
func FormatToken(id APIKeyID, s Secret) (string, error) {
	if id == "" {
		return "", fmt.Errorf("identity: format token: blank key id")
	}
	if len(s.bytes) != SecretEntropyBytes {
		return "", fmt.Errorf("identity: format token: %w", errSecretLength)
	}
	return TokenPrefix(id) + base64.RawURLEncoding.EncodeToString(s.bytes), nil
}

// ParseToken is the fail-closed front door of verification. Every failure —
// wrong brand, wrong shape, bad UUID case, bad base64, wrong secret length,
// any whitespace anywhere in the presented value — returns ErrMalformedToken
// and never says which check tripped, so the error cannot be turned into a
// parser probing whether a value is "almost" a key.
//
// The split is SplitN on "_" with a limit of 3 because the secret's base64url
// alphabet itself contains underscores; the third segment may legally hold
// any number of them.
func ParseToken(raw string) (APIKeyID, Secret, error) {
	// Whitespace anywhere is disqualification, before anything else: a
	// token pasted with a trailing newline must not be rescued by a trim
	// (trimming would make the acceptance depend on the padding, and a
	// verifier that accepts "token " and "token" differently is a probe).
	if strings.IndexFunc(raw, func(r rune) bool {
		return r == ' ' || r == '\t' || r == '\n' || r == '\r' || r == '\v' || r == '\f'
	}) >= 0 {
		return "", Secret{}, fmt.Errorf("identity: parse token: %w: whitespace in token", ErrMalformedToken)
	}
	parts := strings.SplitN(raw, "_", 3)
	if len(parts) != 3 {
		return "", Secret{}, fmt.Errorf("identity: parse token: %w: want brand, id and secret", ErrMalformedToken)
	}
	if parts[0] != TokenBrand {
		return "", Secret{}, fmt.Errorf("identity: parse token: %w: unknown brand", ErrMalformedToken)
	}
	id := APIKeyID(parts[1])
	if err := validateUUIDForm(parts[1]); err != nil {
		return "", Secret{}, fmt.Errorf("identity: parse token: %w: %v", ErrMalformedToken, err)
	}
	encoded := parts[2]
	if len(encoded) != secretEncodedLen {
		return "", Secret{}, fmt.Errorf("identity: parse token: %w: secret segment must be %s characters", ErrMalformedToken, strconv.Itoa(secretEncodedLen))
	}
	rawSecret, err := base64.RawURLEncoding.DecodeString(encoded)
	if err != nil {
		return "", Secret{}, fmt.Errorf("identity: parse token: %w: secret is not base64url", ErrMalformedToken)
	}
	secret, err := NewSecretFromTokenBytes(rawSecret)
	if err != nil {
		return "", Secret{}, fmt.Errorf("identity: parse token: %w: %v", ErrMalformedToken, err)
	}
	return id, secret, nil
}

// validateUUIDForm checks the canonical lowercase 8-4-4-4-12 hex shape. This
// is a grammar check for token parsing — it deliberately does not accept the
// braced or uppercase variants, because a presented token only ever contains
// the form newUUID produced.
func validateUUIDForm(s string) error {
	if len(s) != 36 {
		return errors.New("id must be 36 characters")
	}
	for i, r := range s {
		switch i {
		case 8, 13, 18, 23:
			if r != '-' {
				return errors.New("dashes are misplaced")
			}
		default:
			if !isLowerHex(r) {
				return errors.New("id is not lowercase hex")
			}
		}
	}
	return nil
}

func isLowerHex(r rune) bool {
	return (r >= '0' && r <= '9') || (r >= 'a' && r <= 'f')
}
