package identity

import (
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
)

// The key-material model. A presented API key is a token with the grammar
//
//	gw_<key-id>_<secret>
//
// where <key-id> is the key's RFC 4122 UUID and <secret> is the base64url
// (unpadded) rendering of 32 uniformly random bytes — 256 bits of entropy,
// generated by crypto/rand at mint time. SHA-256 of the raw secret bytes is
// the digest a credential record stores; equality of two fixed-width
// digests is decided by subtle.ConstantTimeCompare, never by ==.
//
// Why SHA-256 and not a password hash: the secret is uniformly random at
// 256 bits, so there is no dictionary to slow down and no benefit from a
// memory-hard function's cost on the runtime hot path. A preimage-resistant
// digest of a high-entropy secret is the standard machinery, and ADR 0006 §9
// already pins exactly this shape for the management-plane service
// credentials. Why the digest lives off the ownership record: ADR 0006 §8, as
// amended by ADR 0007 — the Control Plane keeps the ownership record
// digest-free, and the digest exists on this side of the split only inside the
// credential projection's own tables (the change log and its mirror, ADR 0007
// §1–2), through which it transits to the Data Plane's credential record. The
// ownership aggregate does not carry it, and nothing that reads one reaches
// it.

const (
	// TokenBrand is the fixed first segment of every token this gateway
	// mints. It makes a stray value recognisable as an attempt at a gateway
	// key rather than some other bearer credential.
	TokenBrand = "gw"

	// SecretEntropyBytes is the secret's size in raw bytes. 32 bytes of
	// crypto/rand output is 256 bits — beyond brute force for any
	// foreseeable adversary, and exactly one base64url block short of
	// nothing: it encodes to 43 characters, unpadded.
	SecretEntropyBytes = 32

	// secretEncodedLen is base64.RawURLEncoding.EncodedLen(SecretEntropyBytes).
	// ParseToken checks it so a truncated or padded secret fails closed.
	secretEncodedLen = 43
)

// errSecretLength is a construction-time guard local to this file's grammar
// checks; the caller-facing sentinels live in errors.go and this one is
// always wrapped inside them.
var errSecretLength = errors.New("identity: secret must decode to 32 bytes")

// Secret is one minted key secret. The bytes are never exported: nothing
// outside this package can print, marshal or compare them except through
// the accessors below, every one of which is deliberate. String and GoString
// redact so a log line, an error wrap or a %v of a struct holding a Secret
// shows "redacted" instead of credential material; MarshalText refuses so an
// accidental JSON round-trip cannot smuggle the bytes into a snapshot.
//
// That redaction net has one structural limit, recorded here so the next
// aggregate avoids it: fmt cannot invoke methods on unexported fields, so a
// Secret stored AS A STRUCT FIELD dumps its raw bytes under %v regardless of
// these methods. The contract above holds only while Secret values travel as
// themselves — arguments, returns, interface values — never nested in another
// struct. Nothing today nests one; nothing later may. Go cannot zeroize either
// the secret bytes or the minted token string: the garbage collector may retain
// copies, so never logging and never nesting are the working mitigations, not
// erasure.
type Secret struct {
	bytes []byte
}

// GenerateSecret draws a fresh secret from crypto/rand. Failure is
// effectively impossible on a healthy kernel but is reported, never
// swallowed — minting must not proceed with a weaker secret and must not
// pretend one was made.
func GenerateSecret() (Secret, error) {
	b := make([]byte, SecretEntropyBytes)
	if _, err := rand.Read(b); err != nil {
		return Secret{}, fmt.Errorf("identity: generate secret: %w", err)
	}
	return Secret{bytes: b}, nil
}

// NewSecretFromTokenBytes rebuilds a Secret from the raw bytes decoded out
// of a presented token. It is the only way a Secret enters the system
// besides GenerateSecret, and it enforces the same size bar so a
// wrong-length presentation is malformed, not merely unmatched.
func NewSecretFromTokenBytes(raw []byte) (Secret, error) {
	if len(raw) != SecretEntropyBytes {
		return Secret{}, fmt.Errorf("identity: %w: got %d", errSecretLength, len(raw))
	}
	return Secret{bytes: raw}, nil
}

// Digest returns the SHA-256 of the secret's raw bytes. This is the value a
// credential record stores — never the secret itself.
func (s Secret) Digest() Digest {
	sum := sha256.Sum256(s.bytes)
	return Digest(sum)
}

// String implements fmt.Stringer with a redaction, so every accidental
// printing path — %v, %s, error wrapping, struct dumps — shows a marker
// instead of credential material.
func (s Secret) String() string { return "secret(redacted)" }

// GoString covers the %#v debugging verb with the same redaction.
func (s Secret) GoString() string { return "identity.Secret{redacted}" }

// MarshalText refuses: any encoder that reaches for textual form (JSON,
// maps, structured logs) gets an error rather than credential bytes.
func (s Secret) MarshalText() ([]byte, error) {
	return nil, errors.New("identity: secret must never be serialised")
}

// Digest is a SHA-256 output: fixed-width, byte-comparable, and not itself
// secret material — knowing it does not let anyone present the key, which is
// exactly why it may be stored in a credential record while the secret may
// not. Hex is provided for the places a digest must be rendered (the
// credential projection delivers and stores it in this form — ADR 0007).
type Digest [sha256.Size]byte

// Hex renders the digest lowercase-hex, the canonical text form for storage
// and transport. Harmless to log; not credential material.
func (d Digest) Hex() string {
	const hexDigits = "0123456789abcdef"
	out := make([]byte, 0, 2*sha256.Size)
	for _, b := range d {
		out = append(out, hexDigits[b>>4], hexDigits[b&0x0f])
	}
	return string(out)
}

// EqualDigests compares two digests in constant time. The widths are fixed
// by the type — [32]byte, not slices — so the comparison cannot leak through
// an early exit on length, and the branch on its result happens only after
// the full comparison has run.
func EqualDigests(a, b Digest) bool {
	return subtle.ConstantTimeCompare(a[:], b[:]) == 1
}

// ErrDigestShape reports a stored digest that is not the canonical text form:
// not lowercase hex of exactly Digest's width. Every digest this system stores
// — a session row's token_hash, a credential projection's — is lowercase hex,
// and the columns that hold them carry a shape CHECK saying so.
var ErrDigestShape = errors.New("identity: digest is not lowercase hex of the required width")

// DigestFromHex is the inverse of Hex, and it lives here rather than in an
// adapter for the same reason Hex lives here: a digest's text form is this
// type's business, and an adapter that reimplemented the decode would be a
// second definition of the encoding that the two could disagree about.
//
// It is STRICT where encoding/json and strconv are lenient. `hex.DecodeString`
// accepts uppercase, and a decoder that did the same would answer "yes" for
// two spellings of one digest — which matters here because the value being
// decoded is what a lookup is keyed on, and a canonicalisation applied on the
// way out but not on the way in is a way for two rows to compare equal as
// bytes and differ as text. The width is checked for the same reason: a short
// digest padded to Digest's width would match a different session's row.
func DigestFromHex(encoded string) (Digest, error) {
	var d Digest
	if len(encoded) != hex.EncodedLen(len(d)) {
		return Digest{}, fmt.Errorf("identity: %w: %d characters, want %d", ErrDigestShape, len(encoded), hex.EncodedLen(len(d)))
	}
	for i := range encoded {
		// Uppercase is refused rather than folded: the canonical form is
		// lowercase, and accepting both would make the text form of a stored
		// digest depend on which writer produced it.
		if c := encoded[i]; c >= 'A' && c <= 'F' {
			return Digest{}, fmt.Errorf("identity: %w: uppercase hex", ErrDigestShape)
		}
	}
	decoded, err := hex.DecodeString(encoded)
	if err != nil {
		return Digest{}, fmt.Errorf("identity: %w: %v", ErrDigestShape, err)
	}
	copy(d[:], decoded)
	return d, nil
}

// TokenPrefix renders the public token prefix for a key id: brand and id,
// no secret. It is what consoles show and what the ownership record stores.
func TokenPrefix(id APIKeyID) string {
	return TokenBrand + "_" + string(id) + "_"
}

// FormatToken assembles a full token from its parts at mint time. It is the
// only producer of complete tokens; nothing ever re-formats one later, and
// the returned string is handed to the operator exactly once. Its errors are
// plain programming-error wraps — the arguments come from mint itself, not
// from an untrusted presentation, so the presentation sentinels do not
// apply, and detail that would arm a probing verifier is here exactly where
// it belongs: in front of a developer. The id check is the same grammar
// ParseToken enforces, so a token minted here is a token that parses — a
// minted credential that could never authenticate would fail silently at
// exactly the moment an operator is copying it somewhere safe.
func FormatToken(id APIKeyID, s Secret) (string, error) {
	if err := validateUUIDForm(string(id)); err != nil {
		return "", fmt.Errorf("identity: format token: %w", err)
	}
	if len(s.bytes) != SecretEntropyBytes {
		return "", fmt.Errorf("identity: format token: %w", errSecretLength)
	}
	return TokenPrefix(id) + base64.RawURLEncoding.EncodeToString(s.bytes), nil
}

// ParseToken is the fail-closed front door of verification. Every failure —
// wrong brand, wrong shape, bad UUID, non-canonical base64, wrong secret
// length, any whitespace anywhere in the presented value — returns the
// ErrMalformedToken sentinel itself, with no per-check detail: the sentinel's
// text is byte-identical on every rejection path, so an error echoed to a
// console, a log or an API response cannot be turned into a parser probing
// which stage of the grammar a value reached. The checks themselves keep
// their detail internally — the same grammar guards mint-time producers,
// where the detail fronts a developer rather than a prober.
//
// The split is SplitN on "_" with a limit of 3 because the secret's base64url
// alphabet itself contains underscores; the third segment may legally hold
// any number of them. The decode is base64's strict mode: a canonical
// encoding is required, so one credential has exactly one spelling — the
// non-strict decoder would accept four, and four textual aliases of one
// token defeat any audit or rate limit keyed on the presented string.
func ParseToken(raw string) (APIKeyID, Secret, error) {
	// Whitespace anywhere is disqualification, before anything else: a
	// token pasted with a trailing newline must not be rescued by a trim
	// (trimming would make the acceptance depend on the padding, and a
	// verifier that accepts "token " and "token" differently is a probe).
	if strings.IndexFunc(raw, func(r rune) bool {
		return r == ' ' || r == '\t' || r == '\n' || r == '\r' || r == '\v' || r == '\f'
	}) >= 0 {
		return "", Secret{}, ErrMalformedToken
	}
	parts := strings.SplitN(raw, "_", 3)
	if len(parts) != 3 {
		return "", Secret{}, ErrMalformedToken
	}
	if parts[0] != TokenBrand {
		return "", Secret{}, ErrMalformedToken
	}
	id := APIKeyID(parts[1])
	if err := validateUUIDForm(parts[1]); err != nil {
		return "", Secret{}, ErrMalformedToken
	}
	encoded := parts[2]
	if len(encoded) != secretEncodedLen {
		return "", Secret{}, ErrMalformedToken
	}
	rawSecret, err := base64.RawURLEncoding.Strict().DecodeString(encoded)
	if err != nil {
		return "", Secret{}, ErrMalformedToken
	}
	secret, err := NewSecretFromTokenBytes(rawSecret)
	if err != nil {
		return "", Secret{}, ErrMalformedToken
	}
	return id, secret, nil
}

// validateUUIDForm checks the canonical lowercase 8-4-4-4-12 hex shape,
// including RFC 4122's version nibble (4) and variant bits (10 — one of
// 8, 9, a, b). This is a grammar check for token parsing — it deliberately
// does not accept the braced or uppercase variants, because a presented
// token only ever contains the form newUUID produced, and newUUID sets
// those bits. Its messages carry the detail the grammar check is allowed
// to carry: they surface only on mint-time producers, never through
// ParseToken, which discards them and returns the bare presentation
// sentinel.
func validateUUIDForm(s string) error {
	return validateCanonicalUUIDForm(s, "api key id")
}

// validateCanonicalUUIDForm is the grammar those producers share, with the
// noun the message names supplied by the caller rather than written in. The
// shape is the same for every identifier this package mints — they are all
// newUUID's output — and the only thing that differs between them is what a
// refusal should call the thing it refused. A second copy of the shape
// would be a second grammar, and the copies would drift at the version
// nibble first, where the drift is invisible until two identifiers disagree
// about what a canonical identifier is.
func validateCanonicalUUIDForm(s, noun string) error {
	if len(s) != 36 {
		return fmt.Errorf("%s must be 36 characters", noun)
	}
	for i, r := range s {
		switch i {
		case 8, 13, 18, 23:
			if r != '-' {
				return fmt.Errorf("%s dashes are misplaced", noun)
			}
		case 14:
			if r != '4' {
				return fmt.Errorf("%s is not a version 4 uuid", noun)
			}
		case 19:
			if r != '8' && r != '9' && r != 'a' && r != 'b' {
				return fmt.Errorf("%s is not an rfc 4122 variant", noun)
			}
		default:
			if !isLowerHex(r) {
				return fmt.Errorf("%s is not lowercase hex", noun)
			}
		}
	}
	return nil
}

func isLowerHex(r rune) bool {
	return (r >= '0' && r <= '9') || (r >= 'a' && r <= 'f')
}
