package identity

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"
	"time"
)

// The session aggregate. A session is a browser credential — opaque,
// server-side, stored hashed. Its token is a 256-bit random value
// generated by crypto/rand at mint time; SHA-256 of the raw token bytes
// is the digest a session row stores. Equality of two fixed-width
// digests is decided by subtle.ConstantTimeCompare, never by ==.
//
// Why SHA-256 and not a password hash: the token is uniformly random at
// 256 bits, so there is no dictionary to slow down and no benefit from a
// memory-hard function's cost on the runtime hot path. A preimage-resistant
// digest of a high-entropy secret is the standard machinery.
//
// The token grammar is not gw_ — a session is not an API key and the
// runtime credential is not a console identity. The brand is "ses" so a
// stray value is recognisable as a session token without ambiguity.
const (
	SessionTokenBrand   = "ses"
	SessionTokenBytes   = 32
	sessionTokenEncoded = 43 // base64.RawURLEncoding.EncodedLen(SessionTokenBytes)
)

// SessionID identifies one session. It is the opaque token's public
// prefix material — the token itself is the full ses_<id>_<secret>; the
// id segment is what appears in logs and what the session row's primary
// key is. It is not secret.
type SessionID string

// SessionClass is the holder's authorisation class. It says what the
// holder may do across accounts. This is orthogonal to PrincipalKind:
// PrincipalKind says which credential authenticated (user vs api_key);
// SessionClass says what that holder is authorised as (user acts for one
// account, operator administers several). The two live on different
// types because conflating them would either invent a third credential
// kind the runtime has no way to present, or demote user/operator to a
// redeclaration of what Kind already says. ADR 0012 §2 records this.
type SessionClass string

const (
	// SessionUser: the holder acts for exactly one account.
	SessionUser SessionClass = "user"
	// SessionOperator: the holder administers accounts across accounts.
	// Not minted by any surface this change ships — admitted in the
	// vocabulary and in the contract enum so adding the staff surface
	// later is a new predicate, not a migration over live authorization
	// decisions.
	SessionOperator SessionClass = "operator"
)

// ErrInvalidSessionClass reports a class outside the declared vocabulary.
var ErrInvalidSessionClass = errors.New("identity: invalid session class")

// ParseSessionClass validates a class against the closed vocabulary.
func ParseSessionClass(s string) (SessionClass, error) {
	switch SessionClass(s) {
	case SessionUser, SessionOperator:
		return SessionClass(s), nil
	default:
		return "", fmt.Errorf("identity: %w: %q", ErrInvalidSessionClass, s)
	}
}

// Session is one browser session. The token is returned exactly once at
// creation; the aggregate keeps only its SHA-256 digest. The plaintext
// does not survive this call — no code path in the Control Plane can
// reproduce it after the constructor returns.
type Session struct {
	ID         SessionID
	UserID     UserID
	AccountID  AccountID
	Class      SessionClass
	TokenHash  Digest
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastSeenAt time.Time
	RevokedAt  *time.Time // non-nil exactly when the session is revoked
}

// NewSession constructs a session, generates a 256-bit random token,
// returns the PLAINTEXT exactly once, and keeps only the hash. The
// token format is ses_<session-id>_<secret> where <session-id> is a
// UUIDv4 and <secret> is 32 random bytes base64url-encoded.
func NewSession(userID UserID, accountID AccountID, class SessionClass, ttl time.Duration, now time.Time) (*Session, string, error) {
	if userID == "" {
		return nil, "", fmt.Errorf("identity: new session: blank user id")
	}
	if accountID == "" {
		return nil, "", fmt.Errorf("identity: new session: blank account id")
	}
	if _, err := ParseSessionClass(string(class)); err != nil {
		return nil, "", err
	}
	if ttl <= 0 {
		return nil, "", fmt.Errorf("identity: new session: ttl must be positive")
	}

	now = now.UTC()
	id, err := newSessionID()
	if err != nil {
		return nil, "", fmt.Errorf("identity: new session: %w", err)
	}

	secret, err := generateSessionSecret()
	if err != nil {
		return nil, "", fmt.Errorf("identity: new session: %w", err)
	}

	token := SessionTokenBrand + "_" + string(id) + "_" + base64.RawURLEncoding.EncodeToString(secret.bytes)
	hash := sha256.Sum256(secret.bytes)

	s := &Session{
		ID:         id,
		UserID:     userID,
		AccountID:  accountID,
		Class:      class,
		TokenHash:  Digest(hash),
		CreatedAt:  now,
		ExpiresAt:  now.Add(ttl),
		LastSeenAt: now,
	}
	return s, token, nil
}

func newSessionID() (SessionID, error) {
	id, err := newUUID()
	if err != nil {
		return "", err
	}
	return SessionID(id), nil
}

func generateSessionSecret() (Secret, error) {
	b := make([]byte, SessionTokenBytes)
	if _, err := rand.Read(b); err != nil {
		return Secret{}, fmt.Errorf("identity: generate session secret: %w", err)
	}
	return Secret{bytes: b}, nil
}

// ErrMalformedSessionToken reports a presented session token that does not
// parse at all. Every failure — wrong brand, wrong shape, bad UUID,
// non-canonical base64, wrong secret length, any whitespace anywhere —
// returns this one sentinel with no per-check detail, so an error echoed
// to a console, a log or an API response cannot be turned into a parser
// probing which stage of the grammar a value reached. The reasoning is
// keymaterial.go's ParseToken, reused rather than re-derived.
var ErrMalformedSessionToken = errors.New("identity: malformed session token")

// ParseSessionToken is the fail-closed front door of session resolution: it
// takes a presented cookie value and returns the session id it claims to
// name plus the Secret whose digest the row stores.
//
// It mirrors ParseToken's discipline in every particular, because the
// threat is the same. Whitespace anywhere disqualifies before anything else
// — a cookie pasted or proxied with a trailing newline must not be rescued
// by a trim, since a verifier that accepts "token " and "token" differently
// is a probe. The split is SplitN on "_" with a limit of 3 because the
// secret's base64url alphabet itself contains underscores. The decode is
// base64's strict mode, so one token has exactly one spelling: the
// non-strict decoder would accept four, and four textual aliases of one
// cookie defeat any audit or rate limit keyed on the presented string.
func ParseSessionToken(raw string) (SessionID, Secret, error) {
	if strings.IndexFunc(raw, func(r rune) bool {
		return r == ' ' || r == '\t' || r == '\n' || r == '\r' || r == '\v' || r == '\f'
	}) >= 0 {
		return "", Secret{}, ErrMalformedSessionToken
	}
	parts := strings.SplitN(raw, "_", 3)
	if len(parts) != 3 {
		return "", Secret{}, ErrMalformedSessionToken
	}
	if parts[0] != SessionTokenBrand {
		return "", Secret{}, ErrMalformedSessionToken
	}
	if err := validateUUIDForm(parts[1]); err != nil {
		return "", Secret{}, ErrMalformedSessionToken
	}
	if len(parts[2]) != sessionTokenEncoded {
		return "", Secret{}, ErrMalformedSessionToken
	}
	rawSecret, err := base64.RawURLEncoding.Strict().DecodeString(parts[2])
	if err != nil {
		return "", Secret{}, ErrMalformedSessionToken
	}
	if len(rawSecret) != SessionTokenBytes {
		return "", Secret{}, ErrMalformedSessionToken
	}
	return SessionID(parts[1]), Secret{bytes: rawSecret}, nil
}

// Expired reports whether the session has passed its expiry instant.
//
// The boundary is half-open and the direction is deliberate: the session is
// live AT its expiry instant and dead one nanosecond after it, so ExpiresAt
// is the last instant at which the session is accepted rather than the
// first at which it is refused. Every instant in this package is normalised
// to UTC before the comparison, so a caller passing a value in any other
// zone — and every time this package stores one arrives in UTC — reaches the
// same verdict rather than a wall-clock accident.
func (s *Session) Expired(now time.Time) bool {
	return now.UTC().After(s.ExpiresAt)
}

// Revoked reports whether the session has been explicitly revoked.
func (s *Session) Revoked() bool {
	return s.RevokedAt != nil
}

// Active reports whether the session is currently valid — not expired,
// not revoked.
func (s *Session) Active(now time.Time) bool {
	return !s.Revoked() && !s.Expired(now)
}

// Revoke marks the session as explicitly revoked at the given instant.
func (s *Session) Revoke(now time.Time) {
	t := now.UTC()
	s.RevokedAt = &t
}

// Touch updates LastSeenAt to the given instant.
func (s *Session) Touch(now time.Time) {
	s.LastSeenAt = now.UTC()
}

// String implements fmt.Stringer with a redaction — the token itself is
// never held by this aggregate after construction, but the digest is not
// secret material and may be shown. A debug line printing a Session
// shows its id and class, never the token.
func (s Session) String() string {
	return fmt.Sprintf("session %s class=%s (token redacted)", s.ID, s.Class)
}

// GoString covers %#v with the same redaction.
func (s Session) GoString() string {
	return fmt.Sprintf("identity.Session{ID: %s, UserID: %s, AccountID: %s, Class: %s, TokenHash: %s, CreatedAt: %s, ExpiresAt: %s, LastSeenAt: %s, RevokedAt: %v}", s.ID, s.UserID, s.AccountID, s.Class, s.TokenHash.Hex(), s.CreatedAt, s.ExpiresAt, s.LastSeenAt, s.RevokedAt)
}

// MarshalJSON refuses. A session value in a JSON log, an audit file or a
// response body would carry its digest — harmless — but the redaction
// discipline is that a credential aggregate never serialises.
func (s Session) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("identity: session %s refuses serialisation: credential material must not land in a log, file or wire format", s.ID)
}
