-- Bootstrap the gateway's primary store: PostgreSQL with TimescaleDB.
--
-- This migration exists to prove the migration pipeline end to end — apply,
-- validate, roll back — and to establish the one thing every future
-- time-series migration depends on: the timescaledb extension. It creates no
-- business schema. Tables arrive with the domains that own them, as their own
-- reviewed migrations (accounts, users, api keys and their like are
-- deliberately absent; the reasoning lives in ecoma-io/llm-gateway#8 and in
-- deploy/postgres/README.md's decision record).
--
-- IF NOT EXISTS is load-bearing: the timescaledb docker image pre-creates
-- this extension in POSTGRES_USER's database when it first builds a volume,
-- so on a fresh local database this migration records itself over work the
-- image already did — the honest no-op — instead of failing on it. On any
-- database that did not come from that image, the extension is created here
-- and this migration is its single reviewable provenance.
CREATE EXTENSION IF NOT EXISTS timescaledb;
